version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 8089:8080
      - 5001:5000
    container_name: jenkinsLocal
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_DATABASE=bitnami_testlink
    volumes:
      - './mysql_db:/bitnami'
  testlink:
    build: 
        context: .
        dockerfile: Dockerfile
    platform: linux/amd64
    image: 'bitnami/testlink:1.9.20-debian-10-r301'
    environment:
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=admin
      - TESTLINK_API_ENABLED=true
      - TESTLINK_EMAIL=admin@admin.com
      - TESTLINK_DATABASE_USER=admin
      - TESTLINK_DATABASE_PASSWORD=admin
      - TESTLINK_SMTP_HOST=smtp.gmail.com
      - TESTLINK_SMTP_PORT=587
      - TESTLINK_SMTP_USER=aaa@aaa.com
      - TESTLINK_SMTP_PASSWORD=your_password
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    user: root
    ports:
      - '81:8080'
      - '443:8443'
    volumes:
      - './testlink_data:/bitnami'
    depends_on:
      - mariadb